#!/system/bin/sh
scripts=$(realpath $0)
scripts_dir=$(dirname ${scripts})
parent_dir=$(dirname ${scripts_dir})

clear
echo "Upgrade xray files."

# Get the latest version tag name，Not ignor Pre-release
latest_version=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases | grep -m 1 -oE '"tag_name": *"v[0-9]+\.[0-9]+\.[0-9]+"' | sed -E 's/.*"([^"]+)".*/\1/')

# Check if latest_version is empty
if [ -z "$latest_version" ]; then
  echo "Failed to retrieve the latest version. Exiting script."
  exit 1  # Exit the script with a non-zero status code to indicate failure
fi

# Construct the download URL (assuming you need the Android ARM64 version)
download_url="https://github.com/XTLS/Xray-core/releases/download/$latest_version/Xray-android-arm64-v8a.zip"

# Set the download filename
filename="Xray-android-arm64-v8a.zip"

# Download the file
echo "Downloading Xray-core version $latest_version ..."
curl -L --progress-bar -o $filename $download_url

# Check if the file was downloaded successfully
if [ -f "${scripts_dir}/$filename" ]; then
  # Stop the xray process
  kill $(pidof xray) > /dev/null 2>&1
  sleep 2
  # Unzip the file and overwrite existing files
  unzip -o $filename -d ${parent_dir}/binary
  # Clean up the zip file
  rm $filename
  echo -e "Xray-core \e[31m$latest_version\e[0m downloaded and extracted to ${parent_dir}/binary/"
  sleep 3
# Run the start.sh script
  ${scripts_dir}/start.sh
else
  echo "File download failed."
  exit 1  # Exit the script with a non-zero status code to indicate failure
fi