name: release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github"
      - "README.md"
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run build.sh
        run: sh build.sh

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag: Prerelease
          tag_name: Prerelease
          files: xray_lite_v*.zip
          prerelease: true
          generate_release_notes: true

          
