name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    paths-ignore:
      - ".github"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run build.sh
        run: sh build.sh

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}    # 使用当前推送的标签作为 Release 的标签
          files: xray_lite_*.zip             # 上传符合此模式的文件
          generate_release_notes: true        # 自动生成 Release 说明
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 确保 Token 正确配置
