name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    paths-ignore:
      - ".github"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run build.sh
        run: sh build.sh

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}    # Use the current pushed tag as the Release tag
          files: xray_lite_v*.zip             # Upload files matching this pattern
          generate_release_notes: true        # Automatically generate Release notes
