name: release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github"
      - "README.md"
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run build.sh
        run: sh build.sh

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag_name: ${{ github.ref_name }}  # 使用推送的标签作为 Release 标签
          files: *xray_lite_v*.zip           # 上传符合此模式的文件
          prerelease: true                  # 标记为 Prerelease
          generate_release_notes: true      # 自动生成 Release 说明
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 提供 GitHub Token
